### ISSUE TITLE
在linux(docker)环境下，调用NET_DVR_Login_V30会提示：NET_DVR_NETWORK_ERRORDATA-传送的数据有误

### ISSUE THREAD

**Issue by xuzhenlei** [QuickNV/QuickNV.HikvisionNetSDK#3]
在linux(docker)环境下，调用NET_DVR_Login_V30会提示：NET_DVR_NETWORK_ERRORDATA-传送的数据有误
备注：在windows环境下是正常的

**Comment by aaasoft** [comment]
我只是打包了一下海康的SDK。这个问题你得找海康的技术支持解决哈。

**Comment by xuzhenlei** [comment]
好的。我测试过了，只支持centos，不支持ubuntu，alpine等
